version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:us-east-1:185187793433:task-definition/bluegreen_taskdef:1"
       LoadBalancerInfo:
         ContainerName: "bluegreen"
         ContainerPort: 8080
